version: '3'
services:
    mysql_5.7:
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: "root"
        image: "mysql:5.7" 
        #restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306/tcp"
            - "33060:33060/tcp"
    # mysql_8.0.15:
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "root"
    #     image: "mysql:8.0.15" 
    #     #restart: always
    #     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #     ports:
    #         - "3307:3306/tcp"
    #         - "33070:33060/tcp"
    postgres_latest:
        environment:
            TZ: Asia/Shanghai
            POSTGRES_PASSWORD: "postgres"
        image: "postgres:latest" 
        #restart: always
        ports:
            - "5432:5432/tcp"
    redis_latest:
        image: "redis:latest" 
        environment:
            TZ: Asia/Shanghai
        #restart: always
        ports:
            - "6379:6379/tcp"
    # nginx_latest:
    #     image: "nginx:latest" 
    #     #restart: always
    #     ports:
    #         - "80:80/tcp"
    # node_latest:
    #     image: "node:latest" 
    #     #restart: always
    #     user: "node"
    #     working_dir: /home/node/app
    #     environment:
    #         - TZ=Asia/Shanghai
    #         - NODE_ENV=production
    #     volumes:
    #         - /docker-share/node:/home/node/app
    #     ports:
    #         - 1234:1234
    #     command: "npm start"

    jenkins_latest:
        image: "jenkins/jenkins:lts" 
        environment:
            TZ: Asia/Shanghai
        #restart: always
        #user: "root"
        volumes:
            - "/docker-share/jenkins_home:/var/jenkins_home"
        ports:
            - "8080:8080/tcp"
            - "50000:50000/tcp"
